Develop
NikitaNazarov1/Hound pull request #2
Opened 2019-07-18 09:31 UTC by NikitaNazarov1

2019-07-22 11:36 UTC, KaterinaSav requested changes

2019-07-22 11:36 UTC, KaterinaSav commented on script.rb
> +end
По рубокопу все отлично.
А стайлгайд нужно посмотреть еще раз и переделать все ошибки, что найдешь тут. Задача сделать код максимально красивым)

2019-07-23 10:29 UTC, KaterinaSav requested changes

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +    _result = if !string.empty?
тк проверяешь на `если не`, то лучше сделать `if string.empty?` и поменять местами результат

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +                string.gsub(/[ ,.\r\n]/, ' ').split(' ').each_with_object(Hash.new(0)) do |word, result|
split может получать регекс в параметрах

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +    sort = ->(_word, occurencies) do occurencies; end
https://github.com/rubocop-hq/ruby-style-guide#single-line-blocks

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +  def number_to_word(number)
Разделение на 2 метода делает код менее читабельным.

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +    case number
when then сократит количество строк

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +starts, there was nothing about the cloudy sky outside to suggest that
4 символа отступ

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +    histogram.sort_by { |word, occurencies| sort.call(word, occurencies) }.to_h
зачем здесь вообще лямбда?

2019-07-23 10:29 UTC, KaterinaSav commented on script.rb
> +    puts(histogram)
```
puts('generated histogram:')
puts(histogram)
``` 
можно совместить в 1 строку

2019-07-23 10:40 UTC, NikitaNazarov1 commented on script.rb
> +    puts(histogram)
done

2019-07-23 10:42 UTC, NikitaNazarov1 commented on script.rb
> +starts, there was nothing about the cloudy sky outside to suggest that
done

2019-07-23 10:44 UTC, NikitaNazarov1 commented on script.rb
> +    case number
done

2019-07-23 10:45 UTC, NikitaNazarov1 commented on script.rb
> +  def number_to_word(number)
Fixed

2019-07-23 10:52 UTC, NikitaNazarov1 commented on script.rb
> +    sort = ->(_word, occurencies) do occurencies; end
Fix

2019-07-23 10:53 UTC, NikitaNazarov1 commented on script.rb
> +    histogram.sort_by { |word, occurencies| sort.call(word, occurencies) }.to_h
Fix

2019-07-23 10:55 UTC, NikitaNazarov1 commented on script.rb
> +    _result = if !string.empty?
fix

2019-07-23 11:05 UTC, NikitaNazarov1 commented on script.rb
> +                string.gsub(/[ ,.\r\n]/, ' ').split(' ').each_with_object(Hash.new(0)) do |word, result|
fix

2019-07-23 11:14 UTC, KaterinaSav approved these changes

2019-07-23 13:43 UTC, closed without merging