Task 1 for metaprogramming
NikitaNazarov1/Hound pull request #3
Opened 2019-07-18 13:04 UTC by NikitaNazarov1

2019-07-19 14:37 UTC, KaterinaSav requested changes
По рубокопу все отлично.
А  [стайлгайд](https://github.com/rubocop-hq/ruby-style-guide) нужно посмотреть еще раз и переделать все ошибки, что найдешь тут. Задача сделать код максимально красивым)

2019-07-19 15:09 UTC, KaterinaSav commented on zadanie1.rb
> +puts x
В данном случае это сработает, а что если класс будет такой 
```
class A
  def initialize
    @a = 11
    @@a = 22
    a = 33
    b=43
  end
  @a = 1
  @@a = 2
  a = 3
      b=4
end
```
попробуй тут вывести 33 и 3

2019-07-22 09:49 UTC, NikitaNazarov1 commented on zadanie1.rb
> +puts x
Так это же локальные переменные, к ним извне класса не получишь доступ

2019-07-22 13:10 UTC, NikitaNazarov1 commented on zadanie1.rb
> +puts x
Done

2019-07-23 09:40 UTC, KaterinaSav approved these changes

2019-07-23 13:43 UTC, closed without merging