Task 3 for metaprogramming
NikitaNazarov1/Hound pull request #5
Opened 2019-07-18 13:27 UTC by NikitaNazarov1

2019-07-22 11:44 UTC, KaterinaSav requested changes

2019-07-22 11:44 UTC, KaterinaSav commented on task3.rb
> +
создай метод всеми способами 
- def aninal.speak
- singleton class
- define_method
- instance_eval
- module, extend
- module, include
- send, lambda

2019-07-23 09:00 UTC, NikitaNazarov1 commented on task3.rb
> +
Done

2019-07-23 09:39 UTC, KaterinaSav approved these changes

2019-07-23 13:44 UTC, closed without merging