Task 4 for metaprrogramming
NikitaNazarov1/Hound pull request #6
Opened 2019-07-18 13:36 UTC by NikitaNazarov1

2019-07-22 11:50 UTC, KaterinaSav requested changes

2019-07-22 11:50 UTC, KaterinaSav commented on task4.rb
> +p eval('[@@a, @a, a]', the_binding, __FILE__, __LINE__) # Replace '*****' to your code
Нужно сделать без присваивания the_binding

2019-07-22 12:54 UTC, NikitaNazarov1 commented on task4.rb
> +p eval('[@@a, @a, a]', the_binding, __FILE__, __LINE__) # Replace '*****' to your code
Done

2019-07-23 09:37 UTC, KaterinaSav approved these changes

2019-07-23 13:43 UTC, closed without merging